### ISSUE TITLE
Reimplement JD and BNC platform pages

### ISSUE THREAD

**Issue by ben-pr-p** [BrandNewCongress/core#15]
`brandnewcongress.org/platform` and `justicedemocrats.com/platform` should look the same as `localhost:4000/platform?brand=bnc` and `localhost:4000/platform?brand=jd`

**Comment by seangtkelley** [comment]
Should the platform text content be hardcoded or will it be loaded from an external source?

**Comment by ben-pr-p** [comment]
Check out the `add/platform-page` branch – there's already text there being loaded from our CosmicJS interface

**Comment by ben-pr-p** [comment]
Closed by https://github.com/BrandNewCongress/core/pull/34
